animal = "  perrito Grande  "
print(animal.upper())
print(animal.lower())
print(animal.strip().capitalize())
print(animal.title())
print(animal.strip())
print(animal.lstrip())
print(animal.rstrip())
print(animal.find("rr"))
print(animal.replace("rr", "jj"))
print("rr" in animal)
print("rr" not in animal)
